baseurl: /yinkouya.github.io

# Site settings
title: kouya
author: kouya
description: "building a personal blog using Jekyll on GitHub"
url: "https://yinkouya.github.io/"

gems:
  - jemoji

# github pages and jekyll local use different setting for emoji!
gems: ["emoji_for_jekyll"]

encoding: "utf-8"
highlighter: rouge
future: true
