baseurl: /yinkouya.github.io

# Site settings
title: Weiya
author: Weiya
description: "Going to put some lyrics here cos obvisouly I can't write anything. Love emoji :love_letter:"
url: "https://yinkouya.github.io/"

gems:
  - jemoji
  
encoding: "utf-8"
highlighter: rouge
future: true
